os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - sdk install gradle 6.1
  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
script:
  - ./flutter/bin/flutter -v build apk

cache:
  directories:
    - $HOME/.pub-cache